themes:
  - name: Light
    applicationBackground: f0f3f9
    textColor: 000000
    operatorBackground: f7f9fc
    numbersBackground: 000000
    btnEqualTextColor: 000000
    btnEqualBackground: 0067c0


  - name: Dark
    applicationBackground: 1c2028
    textColor: ff00ea
    operatorBackground: f7f9fc
    numbersBackground: ff00ea
    btnEqualTextColor: ff00ea
    btnEqualBackground: 4cc2ff
